baseURL = 'https://expertpicks.net'
languageCode = 'en-us'
title = 'Expert Picks - Product Reviews & Analysis'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
  env = "production"
  title = "Expert Picks"
  description = "Expert product reviews, in-depth analysis and comprehensive buying guides"
  author = "Expert Picks Team"
  
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.homeInfoParams]
    Title = "🎯 Expert Product Reviews & Analysis"
    Content = "Welcome to Expert Picks - Your trusted source for comprehensive product reviews and buying guides."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "reviews"
    name = "Reviews"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30